<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6326" started-at="2017-11-09T14:26:48Z" finished-at="2017-11-09T14:26:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6326" started-at="2017-11-09T14:26:48Z" finished-at="2017-11-09T14:26:54Z">
      <class name="org.gradle.rbbTest">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:org.gradle.rbbTest@b835727]" name="launchBrowser" is-config="true" duration-ms="6193" started-at="2017-11-09T15:26:48Z" finished-at="2017-11-09T15:26:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testcase02()[pri:7, instance:org.gradle.rbbTest@b835727]" name="testcase02" duration-ms="76" started-at="2017-11-09T15:26:54Z" finished-at="2017-11-09T15:26:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [aa] but found [rbb|24 | rbb|24 - Nachrichten aus Berlin und Brandenburg]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [aa] but found [rbb|24 | rbb|24 - Nachrichten aus Berlin und Brandenburg]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at org.gradle.rbbTest.testcase02(rbbTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase02 -->
        <test-method status="PASS" signature="terminateBrowser()[pri:0, instance:org.gradle.rbbTest@b835727]" name="terminateBrowser" is-config="true" duration-ms="28" started-at="2017-11-09T15:26:54Z" finished-at="2017-11-09T15:26:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- org.gradle.rbbTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
